# Generated by Django 5.1.2 on 2024-10-22 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='duration',
        ),
        migrations.AddField(
            model_name='experience',
            name='duration_from_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='experience',
            name='duration_from_year',
            field=models.IntegerField(default=1900),
        ),
        migrations.AddField(
            model_name='experience',
            name='duration_to_month',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='experience',
            name='duration_to_year',
            field=models.IntegerField(default=1900),
        ),
        migrations.AddField(
            model_name='project',
            name='duration_from_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='duration_from_year',
            field=models.IntegerField(default=1900),
        ),
        migrations.AddField(
            model_name='project',
            name='duration_to_month',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='project',
            name='duration_to_year',
            field=models.IntegerField(default=1900),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.CharField(default='N/A', max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=200)),
                ('duration_from_year', models.IntegerField(default=1900)),
                ('duration_from_month', models.IntegerField(default=1)),
                ('duration_to_year', models.IntegerField(default=1900)),
                ('duration_to_month', models.IntegerField(default=12)),
                ('marks_or_grade', models.CharField(max_length=100)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
