# Generated by Django 5.1.2 on 2024-10-22 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_experience_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.userprofile'),
        ),
    ]
